package Forms;

import DataBaseManageAndReport.DatabaseManager;
import DataBaseManageAndReport.Employee;
import FutureUpdates.AddNewLocationContract;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;

/**
 * Created by mohab 2 on 11/23/2016.
 */
public class ManagementPage {

    private JPanel panel1;
    private JButton طباعةالفواتيرButton;
    private JButton إدارةالتعاقداتButton;
    private JButton إدارةالحساباتالبنكيةButton;
    private JButton خروجButton;
    private JButton تغييربياناتالشركةالأساسيةButton;
    private JButton btn_contr_management;
    private JLabel lbl_NumberOfEmployees;
    private JLabel lbl_NumberOfContracts;
    private JLabel lbl_income;
    private JLabel lbl_TotalSalaries;
    private String sql;
    private String dbName = Employee.EmpDBName;
    private DatabaseManager dbManager = new DatabaseManager();
    Locale arabicLocale = new Locale.Builder().setLanguageTag("ar-SA-u-nu-arab").build();
    NumberFormat numberFormat = NumberFormat.getNumberInstance(arabicLocale);

    public ManagementPage() throws SQLException {

        panel1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        for (Component c : panel1.getComponents()
                ) {
            c.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        }


        خروجButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
        طباعةالفواتيرButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    new PrintBills().main(null);
                } catch (SQLException e1) {
                    e1.printStackTrace();
                }
            }
        });
        إدارةالتعاقداتButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    new CompanyBills_MainSettings().main(null);
                } catch (SQLException e1) {
                    e1.printStackTrace();
                }
            }
        });
        إدارةالحساباتالبنكيةButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    new BankAccountsManagement().main(null);
                } catch (SQLException e1) {
                    e1.printStackTrace();
                }
            }
        });
        تغييربياناتالشركةالأساسيةButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    new company_settings().main(null);
                } catch (SQLException e1) {
                    e1.printStackTrace();
                }
            }
        });
        btn_contr_management.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    new AddNewLocationContract().main(null);
                } catch (ParseException e1) {
                    e1.printStackTrace();
                } catch (SQLException e1) {
                    e1.printStackTrace();
                }
            }
        });
    }


    public static void main(String[] args) throws SQLException {
        ManagementPage managementPage = new ManagementPage();
        int screenWidth = (int) Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        int screenHeight = (int) Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        Employee.setLookAndFeelForMyProgram();
        JFrame frame = new JFrame();
        frame.add(managementPage.panel1);
        SwingUtilities.updateComponentTreeUI(frame);
        frame.setVisible(true);
        frame.setBounds(screenWidth / 3, screenHeight / 8, 200, 600);
        frame.setResizable(false);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:148px:grow", "center:max(d;90px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;90px):noGrow,top:4dlu:noGrow,center:max(d;90px):noGrow,top:4dlu:noGrow,center:max(d;90px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;90px):noGrow"));
        طباعةالفواتيرButton = new JButton();
        طباعةالفواتيرButton.setText("طباعة الفواتير");
        CellConstraints cc = new CellConstraints();
        panel1.add(طباعةالفواتيرButton, cc.xywh(1, 1, 1, 3, CellConstraints.DEFAULT, CellConstraints.FILL));
        إدارةالتعاقداتButton = new JButton();
        إدارةالتعاقداتButton.setHideActionText(false);
        إدارةالتعاقداتButton.setText("إدارة التعاقدات");
        panel1.add(إدارةالتعاقداتButton, cc.xy(1, 5, CellConstraints.DEFAULT, CellConstraints.FILL));
        إدارةالحساباتالبنكيةButton = new JButton();
        إدارةالحساباتالبنكيةButton.setText("إدارة الحسابات البنكية");
        panel1.add(إدارةالحساباتالبنكيةButton, cc.xy(1, 7, CellConstraints.DEFAULT, CellConstraints.FILL));
        خروجButton = new JButton();
        خروجButton.setText("خروج");
        panel1.add(خروجButton, cc.xy(1, 13, CellConstraints.DEFAULT, CellConstraints.FILL));
        تغييربياناتالشركةالأساسيةButton = new JButton();
        تغييربياناتالشركةالأساسيةButton.setLabel("تغيير بيانات الشركة الأساسية");
        تغييربياناتالشركةالأساسيةButton.setText("تغيير بيانات الشركة الأساسية");
        panel1.add(تغييربياناتالشركةالأساسيةButton, cc.xy(1, 9, CellConstraints.DEFAULT, CellConstraints.FILL));
        btn_contr_management = new JButton();
        btn_contr_management.setText("إعدادات التعاقدات");
        panel1.add(btn_contr_management, cc.xy(1, 11));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
